[manifest]
version = "1.0.0"
priority = 0

# naneinf crash fixes
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if G.GAME.round_scores[score] and math.floor(amt) > G.GAME.round_scores[score].amt then"
position = "at"
payload = '''
if G.GAME.round_scores[score] and math.floor(amt) > (G.GAME.round_scores[score].amt or 0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "function Game:update_hand_played(dt)"
position = "after"
payload = '''
G.GAME.chips = (G.GAME.chips or 0)
G.GAME.blind.chips = (G.GAME.blind.chips or math.huge)'''
match_indent = true
# Naneinf crash fixes end

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = 'if v.is and v:is(Object) then ret_t[k] = [["]].."MANUAL_REPLACE"..[["]]'
position = 'at'
payload = '''
if Big and Big.is(v) then ret_t[k] = v:as_table()
elseif v.is and v:is(Object) then ret_t[k] = [["]].."MANUAL_REPLACE"..[["]]
'''
match_indent = true