[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''create_option_cycle({label = localize('b_set_gamespeed'),scale = 0.8, options = {0.5, 1, 2, 4}, opt_callback = 'change_gamespeed', current_option = (G.SETTINGS.GAMESPEED == 0.5 and 1 or G.SETTINGS.GAMESPEED == 4 and 4 or G.SETTINGS.GAMESPEED + 1)}),'''
position = "at"
payload = '''
create_option_cycle({
	label = localize('b_set_gamespeed'),
	scale = 0.8,
	options = G.SPEED_OPTIONS,
	opt_callback = 'change_gamespeed',
	current_option = get_index(G.SPEED_OPTIONS, G.SETTINGS.GAMESPEED) or -1
}),
'''

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''G.ACC = math.min((G.ACC or 0) + dt*0.2*self.SETTINGS.GAMESPEED, 16)'''
position = "at"
payload = '''G.ACC = (G.ACC or 0) + dt*0.2*self.SETTINGS.GAMESPEED'''
